# -*- coding: utf-8 -*-
"""Part A - Student COPY - Plotly Demonstration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1__JK-rSiAMDnu52AnNxqGHsFMSH6IAh1

# --- Introduction ---
#### Welcome! In this notebook, you will practice creating interactive visualizations using Plotly Express.
##### Follow the instructions, run the code cells, and explore the outputs!

-- Edit and Write your Name and USN below this line --

- USN - 380
- FULL NAME - Shubanck Guptha
- SECTION - F
- SEMESTER - I
"""

#!pip install plotly
#%pip install seaborn
#In case for installation of ploty and seaborn package uncomment above syntax and execute the cell

# verify the plotly version
!pip show plotly

# verify the seaborn version
!pip show seaborn

# Plotly Workshop - Student Practice Notebook

# Import necessary libraries [ seaborn, plotly and pandas ]
# Write the code below this line

"""#### Load the very simple dataset from seaborn library"""

#1. Load the tips dataset from Seaborn
# Write the code below this line

# Display the first few rows of the dataset
# Write the code below this line

#2. Visualizations using  [ simple plot ]
# Write the code below this line

#3. Bar Chart: Average Tip by Day (With Color)
# Write the code below this line

"""[ Double click and edit the line ] -- Write the inference of the above plot below this line. --"""

#4. Scatter Plot: Total Bill vs. Tip (Color-coded by Gender)
# Write the code below this line

"""[ Double click and edit the line ] -- Write the inference of the above plot below this line. --"""

#5. Box Plot: Distribution of Total Bill by Day (With Color by Time)
# Write the code below this line

"""[ Double click and edit the line ] -- Write the inference of the above plot below this line. --"""

#6. Histogram: Tip Distribution (With Color)
# Write the code below this line

"""[ Double click and edit the line ] -- Write the inference of the above plot below this line. --"""



"""-- End of the Task --"""